apiVersion: v1
kind: Secret
metadata:
  name: go-netconf-secret
type: Opaque
stringData:
  NETCONF_HOST: "om-confd-sb-netconf.ims-oam.svc"
  NETCONF_PORT: "2082"
  NETCONF_USERNAME: "public"
  NETCONF_PASSWORD: "123"