apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-netconf-test
  namespace: default
  labels:
    app: go-netconf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-netconf-test
  template:
    metadata:
      labels:
        app: go-netconf-test
    spec:
      containers:
      - name: go-netconf-test
        image: docker-registry:4000/netconf-test:latest
        imagePullPolicy: Always
      
        env:
        - name: TZ
          value: "Asia/Ho_Chi_Minh"

        envFrom:
        - secretRef:
            name: go-netconf-secret
        - configMapRef:
            name: go-netconf-configmap